default_platform(:tvos)

def build_no()
  return Time.now.strftime("%Y%m%d.%H%M%S")
end


def setVersion()
  version = File.read("../app-version.txt")
  # cmd = "agvtool new-marketing-version " + version
  # `#{cmd}`
  increment_version_number(version_number: version)
  increment_build_number(
    build_number: build_no(),
    xcodeproj: "BilibiliLive.xcodeproj"
  )
end

def testFlightBuildTV()
  sign()
  build_app(
    clean: true,
    scheme: "BilibiliLive",
    xcargs: "-allowProvisioningUpdates",
    output_directory: "build/tvOS",
    archive_path: "build/archive/BilibiliLive-tv.xcarchive",
    destination:"generic/platform=tvOS",
  )
  upload_to_testflight(
    app_platform: "appletvos",
    ipa: "build/tvOS/BilibiliLive-tvOS.ipa",
  )
end


platform :tvos do
  desc "Push a new beta build to TestFlight"
  lane :betaonly do
    testFlightBuildTV()
  end

  desc "Use current version and push a new beta build to TestFlight"
  lane :beta do
    setVersion()
    testFlightBuildTV()
  end

  desc "Change 0.0.x version"
  lane :patch do
    upgradeVersion("patch")
  end

  desc "Change 0.x.0 version"
  lane :minor do
    upgradeVersion("minor")
  end

  desc "Change x.0.0 version"
  lane :major do
    upgradeVersion("major")
  end

  desc "Set app version only"
  lane :version do
    setVersion()
  end

end
